name: CI

on: [push]

jobs:
  linuxbuild:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          sudo apt-get install libsfml-dev
          cd src
          ./make.sh
          mkdir final
          cp -R res final
          rm -rf final/res/levels/.git
          cp Tsuikaban final
      - uses: actions/upload-artifact@v1
        with:
          name: Tsuikaban-amd64
          path: src/final

  winbuild:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Compilazione
        run: |
          choco install devbox-wget
          choco install devbox-unzip
          wget https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-32-bit.zip
          unzip SFML-2.5.1-windows-gcc-7.3.0-mingw-32-bit.zip
          mkdir src/final
          cp SFML-2.5.1/bin/* src/final
          cd src
          g++ main.cpp Game.cpp Editor.cpp LevelSelect.cpp -o Tsuikaban.exe -std=c++14 -O2 -Wall -Wextra -Wpedantic -L../SFML-2.5.1/lib -I../SFML-2.5.1/include -lsfml-system -lsfml-window -lsfml-graphics
          cp -R res final
          rm -rf final/res/levels/.git
          cp Tsuikaban.exe final
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: Tsuikaban-win
          path: src/final
