name: CI

on: [push]

jobs:
  linuxbuild:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          sudo apt-get install libsfml-dev
          cd src
          ./make.sh
          mkdir final
          git submodule update --init --recursive
          cp -R res final
          rm -rf final/res/levels/.git
          cp Tsuikaban final
      - uses: actions/upload-artifact@v1
        with:
          name: Tsuikaban-lin-amd64
          path: src/final

  winbuild:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Compilazione
        run: |
          Invoke-WebRequest -Uri https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip -OutFile sfml.zip
          Expand-Archive sfml.zip
          mv sfml\SFML-2.5.1 .
          New-Item -ItemType directory -Path src\final
          Copy-Item SFML-2.5.1\bin\* src\final
          Copy-Item c:\MinGW\bin\libstdc++-6.dll src\final
          Copy-Item c:\MinGW\bin\libgcc_s_seh-1.dll src\final
          Set-Location -Path src
          g++ main.cpp Game.cpp Editor.cpp LevelSelect.cpp -o Tsuikaban.exe -std=c++14 -O2 -Wall -Wextra -Wpedantic -L../SFML-2.5.1/lib -I../SFML-2.5.1/include -lsfml-system -lsfml-window -lsfml-graphics
          Copy-Item res/* final/res
          Copy-Item Tsuikaban.exe final
          #Remove-Item -LiteralPath final\res\levels\.git -Force -Recurse
        shell: powershell
      - uses: actions/upload-artifact@v1
        with:
          name: Tsuikaban-win-amd64
          path: src/final
